id: I9B92C58B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T11:58:50+00:00'
last_modified: '2022-06-08T12:01:51.107803+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W28883
  title: རྗེ་ཉི་མ་བཀྲ་ཤིས་ཀྱི་རྣམ་མགུར་དང་སྒ་ངག་དབང་ལེགས་པའི་རྣམ་ཐར
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    7D3E:
      image_group_id: I4835
      title: ''
      total_pages: 128
      order: 1
      base_file: 7D3E.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
