id: P009579
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-19 20:39:04.508900
source_metadata:
  id: bdr:W28883
  title: རྗེ་ཉི་མ་བཀྲ་ཤིས་ཀྱི་རྣམ་མགུར་དང་སྒ་ངག་དབང་ལེགས་པའི་རྣམ་ཐར
  author: ''
  volumes:
    5454db386e41489d95340ff93225720e:
      image_group_id: I4835
      title: ''
      volume_number: 1
      total_pages: 128
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
